<?php

namespace Database\Seeders;

use App\Models\Property;
use App\Models\User;
use Illuminate\Database\Seeder;

class PropertySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Use the admin account as the listing agent
        $admin = User::where('email', 'admin@mandreality.com')->first();

        if (!$admin) {
            $this->command->error('Admin user not found! Run AdminUserSeeder first.');
            return;
        }

        $properties = [
            // ── FOR SALE ──────────────────────────────────────────
            [
                'user_id' => $admin->id,
                'property_title' => 'Beautiful Family Home in Tulsa',
                'developer' => 'Simmons Homes',
                'property_type' => 'single-family-home',
                'status' => 'for-sale',
                'listing_status' => 'for_sale',
                'price' => 299000,
                'address' => '1234 S Yorktown Ave',
                'city' => 'Tulsa',
                'state' => 'Oklahoma',
                'zip_code' => '74104',
                'subdivision' => 'Oak Hills',
                'school_district' => 'Tulsa Public Schools',
                'grade_school' => 'Eliot Elementary',
                'middle_school' => 'Edison Preparatory',
                'high_school' => 'Edison High School',
                'bedrooms' => 4,
                'bathrooms' => 3,
                'full_bathrooms' => 3,
                'half_bathrooms' => 0,
                'sqft' => 2500,
                'lot_size' => 10890,
                'acres' => 0.25,
                'year_built' => 2015,
                'description' => 'This stunning 4-bedroom home features an open floor plan, modern kitchen with granite countertops, hardwood floors throughout, and a spacious backyard perfect for entertaining. Located in a quiet neighborhood with easy access to schools and shopping. Recently updated with smart home features and energy-efficient windows.',
                'features' => ['Central AC', 'Central Heat', 'Hardwood Floors', 'Granite Countertops', 'Stainless Steel Appliances', 'Fenced Yard', 'Garage', 'Smart Home', 'Energy Efficient'],
                'photos' => [
                    'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=800',
                    'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800',
                    'https://images.pexels.com/photos/2724749/pexels-photo-2724749.jpeg?auto=compress&cs=tinysrgb&w=800',
                    'https://images.pexels.com/photos/2062426/pexels-photo-2062426.jpeg?auto=compress&cs=tinysrgb&w=800',
                ],
                'contact_name' => 'M&T Realty Group',
                'contact_email' => 'admin@mandreality.com',
                'contact_phone' => '(405) 964-8485',
                'is_active' => true,
                'is_mls_listed' => true,
                'mls_number' => 'MLS-2026-0001',
                'listing_tier' => 'mls',
                'has_professional_photos' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
                'approved_by' => $admin->id,
                'latitude' => 36.1340,
                'longitude' => -95.9520,
            ],
            [
                'user_id' => $admin->id,
                'property_title' => 'Modern Condo in Downtown OKC',
                'developer' => 'Clayco Development',
                'property_type' => 'condos-townhomes-co-ops',
                'status' => 'for-sale',
                'listing_status' => 'for_sale',
                'price' => 215000,
                'address' => '100 W Main St, Unit 804',
                'city' => 'Oklahoma City',
                'state' => 'Oklahoma',
                'zip_code' => '73102',
                'subdivision' => 'Downtown District',
                'school_district' => 'Oklahoma City Public Schools',
                'grade_school' => 'Eugene Field Elementary',
                'middle_school' => 'Taft Middle School',
                'high_school' => 'Classen SAS',
                'bedrooms' => 2,
                'bathrooms' => 2,
                'full_bathrooms' => 2,
                'half_bathrooms' => 0,
                'sqft' => 1200,
                'lot_size' => null,
                'year_built' => 2018,
                'description' => 'Sleek modern condo in the heart of downtown Oklahoma City. Features floor-to-ceiling windows, contemporary finishes, and stunning city views. Building amenities include a fitness center, rooftop deck, concierge service, and secure parking. Walk to Bricktown, Scissortail Park, and the Myriad Gardens.',
                'features' => ['Central AC', 'Central Heat', 'Walk-In Closet', 'Updated Kitchen', 'Security System', 'Balcony', 'Elevator', 'Concierge'],
                'photos' => [
                    'https://images.pexels.com/photos/1643389/pexels-photo-1643389.jpeg?auto=compress&cs=tinysrgb&w=800',
                    'https://images.pexels.com/photos/1571468/pexels-photo-1571468.jpeg?auto=compress&cs=tinysrgb&w=800',
                    'https://images.pexels.com/photos/2030037/pexels-photo-2030037.jpeg?auto=compress&cs=tinysrgb&w=800',
                ],
                'contact_name' => 'M&T Realty Group',
                'contact_email' => 'admin@mandreality.com',
                'contact_phone' => '(405) 964-8485',
                'is_active' => true,
                'is_mls_listed' => true,
                'mls_number' => 'MLS-2026-0002',
                'listing_tier' => 'mls',
                'has_professional_photos' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
                'approved_by' => $admin->id,
                'latitude' => 35.4676,
                'longitude' => -97.5164,
            ],
            [
                'user_id' => $admin->id,
                'property_title' => 'Spacious Ranch Home in Norman',
                'developer' => 'Ideal Homes',
                'property_type' => 'single-family-home',
                'status' => 'for-sale',
                'listing_status' => 'for_sale',
                'price' => 425000,
                'address' => '1200 Pinnacle Dr',
                'city' => 'Norman',
                'state' => 'Oklahoma',
                'zip_code' => '73072',
                'subdivision' => 'University Park',
                'school_district' => 'Norman Public Schools',
                'grade_school' => 'Monroe Elementary',
                'middle_school' => 'Irving Middle School',
                'high_school' => 'Norman High School',
                'bedrooms' => 5,
                'bathrooms' => 3.5,
                'full_bathrooms' => 3,
                'half_bathrooms' => 1,
                'sqft' => 3200,
                'lot_size' => 21780,
                'acres' => 0.50,
                'year_built' => 2010,
                'description' => 'Expansive ranch-style home near the University of Oklahoma. Features include a chef\'s kitchen with double ovens, formal dining room, home office, and finished basement with media room. The large backyard includes an in-ground pool, covered patio with outdoor kitchen, and mature landscaping.',
                'features' => ['Central AC', 'Central Heat', 'Swimming Pool', 'Covered Patio', 'Fireplace', 'Granite Countertops', 'Hardwood Floors', 'Garage', 'Sprinkler System', 'Outdoor Kitchen'],
                'photos' => [
                    'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=800',
                    'https://images.pexels.com/photos/2227832/pexels-photo-2227832.jpeg?auto=compress&cs=tinysrgb&w=800',
                    'https://images.pexels.com/photos/2581922/pexels-photo-2581922.jpeg?auto=compress&cs=tinysrgb&w=800',
                    'https://images.pexels.com/photos/2062426/pexels-photo-2062426.jpeg?auto=compress&cs=tinysrgb&w=800',
                    'https://images.pexels.com/photos/261327/pexels-photo-261327.jpeg?auto=compress&cs=tinysrgb&w=800',
                ],
                'contact_name' => 'M&T Realty Group',
                'contact_email' => 'admin@mandreality.com',
                'contact_phone' => '(405) 964-8485',
                'is_active' => true,
                'is_featured' => true,
                'is_mls_listed' => true,
                'mls_number' => 'MLS-2026-0003',
                'listing_tier' => 'mls',
                'has_professional_photos' => true,
                'has_virtual_tour' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
                'approved_by' => $admin->id,
                'latitude' => 35.2226,
                'longitude' => -97.4395,
            ],
            [
                'user_id' => $admin->id,
                'property_title' => 'Charming Starter Home in Edmond',
                'developer' => 'Landmark Fine Homes',
                'property_type' => 'single-family-home',
                'status' => 'for-sale',
                'listing_status' => 'for_sale',
                'price' => 275000,
                'address' => '1500 E Covell Rd',
                'city' => 'Edmond',
                'state' => 'Oklahoma',
                'zip_code' => '73034',
                'subdivision' => 'Covell Estates',
                'school_district' => 'Edmond Public Schools',
                'grade_school' => 'Northern Hills Elementary',
                'middle_school' => 'Sequoyah Middle School',
                'high_school' => 'Edmond North High School',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'full_bathrooms' => 2,
                'half_bathrooms' => 0,
                'sqft' => 1650,
                'lot_size' => 6534,
                'acres' => 0.15,
                'year_built' => 2012,
                'description' => 'Perfect starter home in the highly sought-after Edmond school district. Features an updated kitchen with quartz countertops, new LVP flooring throughout, fresh paint, and a nice backyard with patio. Move-in ready with a new roof installed in 2024.',
                'features' => ['Central AC', 'Central Heat', 'Updated Kitchen', 'Fenced Yard', 'Garage', 'New Roof', 'Patio'],
                'photos' => [
                    'https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=800',
                    'https://images.pexels.com/photos/1080721/pexels-photo-1080721.jpeg?auto=compress&cs=tinysrgb&w=800',
                    'https://images.pexels.com/photos/2724749/pexels-photo-2724749.jpeg?auto=compress&cs=tinysrgb&w=800',
                ],
                'contact_name' => 'M&T Realty Group',
                'contact_email' => 'admin@mandreality.com',
                'contact_phone' => '(405) 964-8485',
                'is_active' => true,
                'is_mls_listed' => true,
                'mls_number' => 'MLS-2026-0004',
                'listing_tier' => 'mls',
                'has_professional_photos' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
                'approved_by' => $admin->id,
                'latitude' => 35.6528,
                'longitude' => -97.4395,
            ],
            [
                'user_id' => $admin->id,
                'property_title' => 'Luxury Estate in Broken Arrow',
                'developer' => 'Shaw Homes',
                'property_type' => 'single-family-home',
                'status' => 'for-sale',
                'listing_status' => 'for_sale',
                'price' => 725000,
                'address' => '4500 W Kenosha St',
                'city' => 'Broken Arrow',
                'state' => 'Oklahoma',
                'zip_code' => '74012',
                'subdivision' => 'Aspen Creek',
                'school_district' => 'Broken Arrow Public Schools',
                'grade_school' => 'Aspen Creek Elementary',
                'middle_school' => 'Oliver Middle School',
                'high_school' => 'Broken Arrow High School',
                'bedrooms' => 6,
                'bathrooms' => 5.5,
                'full_bathrooms' => 5,
                'half_bathrooms' => 1,
                'sqft' => 4500,
                'lot_size' => 21780,
                'acres' => 0.50,
                'year_built' => 2019,
                'description' => 'Stunning luxury estate with every amenity imaginable. Features include a gourmet kitchen with Sub-Zero and Wolf appliances, wine cellar, dedicated home theater, and resort-style backyard with heated pool, spa, and outdoor kitchen. Smart home technology throughout with Lutron lighting and Sonos whole-home audio.',
                'features' => ['Central AC', 'Central Heat', 'Swimming Pool', 'Hot Tub', 'Fireplace', 'Granite Countertops', 'Hardwood Floors', 'Walk-In Closet', 'Security System', 'Sprinkler System', 'Covered Patio', 'Garage', 'Smart Home', 'Wine Cellar', 'Home Theater'],
                'photos' => [
                    'https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=800',
                    'https://images.pexels.com/photos/1396132/pexels-photo-1396132.jpeg?auto=compress&cs=tinysrgb&w=800',
                    'https://images.pexels.com/photos/2287310/pexels-photo-2287310.jpeg?auto=compress&cs=tinysrgb&w=800',
                    'https://images.pexels.com/photos/261327/pexels-photo-261327.jpeg?auto=compress&cs=tinysrgb&w=800',
                    'https://images.pexels.com/photos/2030037/pexels-photo-2030037.jpeg?auto=compress&cs=tinysrgb&w=800',
                    'https://images.pexels.com/photos/3935350/pexels-photo-3935350.jpeg?auto=compress&cs=tinysrgb&w=800',
                ],
                'contact_name' => 'M&T Realty Group',
                'contact_email' => 'admin@mandreality.com',
                'contact_phone' => '(405) 964-8485',
                'is_active' => true,
                'is_featured' => true,
                'is_showcase' => true,
                'is_mls_listed' => true,
                'mls_number' => 'MLS-2026-0005',
                'listing_tier' => 'mls',
                'has_professional_photos' => true,
                'has_virtual_tour' => true,
                'has_video' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
                'approved_by' => $admin->id,
                'latitude' => 36.0609,
                'longitude' => -95.7975,
            ],
            [
                'user_id' => $admin->id,
                'property_title' => 'Updated Home Near Fort Sill',
                'developer' => 'Homes by Taber',
                'property_type' => 'single-family-home',
                'status' => 'for-sale',
                'listing_status' => 'for_sale',
                'price' => 189000,
                'address' => '1002 SW Lee Blvd',
                'city' => 'Lawton',
                'state' => 'Oklahoma',
                'zip_code' => '73501',
                'subdivision' => null,
                'school_district' => 'Lawton Public Schools',
                'grade_school' => 'Eisenhower Elementary',
                'middle_school' => 'MacArthur Middle School',
                'high_school' => 'Lawton High School',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'full_bathrooms' => 2,
                'half_bathrooms' => 0,
                'sqft' => 1400,
                'lot_size' => 6970,
                'acres' => 0.16,
                'year_built' => 1998,
                'description' => 'Well-maintained and recently updated home near Fort Sill. New roof (2024), new HVAC system, updated electrical panel, and fresh interior paint throughout. Great location for military families with easy base access. Open floor plan with vaulted ceilings in the living room.',
                'features' => ['Central AC', 'Central Heat', 'Fenced Yard', 'Garage', 'Updated Bathroom', 'New Roof', 'Vaulted Ceilings'],
                'photos' => [
                    'https://images.pexels.com/photos/280222/pexels-photo-280222.jpeg?auto=compress&cs=tinysrgb&w=800',
                    'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=800',
                ],
                'contact_name' => 'M&T Realty Group',
                'contact_email' => 'admin@mandreality.com',
                'contact_phone' => '(405) 964-8485',
                'is_active' => true,
                'is_mls_listed' => true,
                'mls_number' => 'MLS-2026-0006',
                'listing_tier' => 'mls',
                'has_professional_photos' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
                'approved_by' => $admin->id,
                'latitude' => 34.6036,
                'longitude' => -98.4003,
            ],
            [
                'user_id' => $admin->id,
                'property_title' => 'Build-Ready Lot in South Moore',
                'developer' => null,
                'property_type' => 'land',
                'status' => 'for-sale',
                'listing_status' => 'for_sale',
                'price' => 89000,
                'address' => '1900 S Eastern Ave',
                'city' => 'Moore',
                'state' => 'Oklahoma',
                'zip_code' => '73160',
                'subdivision' => null,
                'school_district' => 'Moore Public Schools',
                'grade_school' => null,
                'middle_school' => null,
                'high_school' => 'Southmoore High School',
                'bedrooms' => 0,
                'bathrooms' => 0,
                'full_bathrooms' => 0,
                'half_bathrooms' => 0,
                'sqft' => 0,
                'lot_size' => 43560,
                'acres' => 1.0,
                'zoning' => 'R-1 Residential',
                'year_built' => null,
                'description' => 'Beautiful 1-acre lot ready for your dream home. All utilities available at the street including city water, sewer, gas, and electric. Located in a growing area with easy highway access to I-35. No HOA restrictions — bring your own builder. Lightly wooded with mature trees along the perimeter.',
                'features' => ['Mature Trees', 'City Water', 'City Sewer', 'Electric Available', 'Gas Available'],
                'photos' => [
                    'https://images.pexels.com/photos/440731/pexels-photo-440731.jpeg?auto=compress&cs=tinysrgb&w=800',
                ],
                'contact_name' => 'M&T Realty Group',
                'contact_email' => 'admin@mandreality.com',
                'contact_phone' => '(405) 964-8485',
                'is_active' => true,
                'is_mls_listed' => true,
                'mls_number' => 'MLS-2026-0007',
                'listing_tier' => 'mls',
                'approval_status' => 'approved',
                'approved_at' => now(),
                'approved_by' => $admin->id,
                'latitude' => 35.3395,
                'longitude' => -97.4867,
            ],
            [
                'user_id' => $admin->id,
                'property_title' => 'Income-Producing Fourplex in Stillwater',
                'developer' => 'Wallace Engineering',
                'property_type' => 'multi-family',
                'status' => 'for-sale',
                'listing_status' => 'for_sale',
                'price' => 415000,
                'address' => '715 S Husband St',
                'city' => 'Stillwater',
                'state' => 'Oklahoma',
                'zip_code' => '74074',
                'subdivision' => null,
                'school_district' => 'Stillwater Public Schools',
                'grade_school' => null,
                'middle_school' => null,
                'high_school' => 'Stillwater High School',
                'bedrooms' => 8,
                'bathrooms' => 4,
                'full_bathrooms' => 4,
                'half_bathrooms' => 0,
                'sqft' => 3600,
                'lot_size' => 10890,
                'acres' => 0.25,
                'year_built' => 2005,
                'description' => 'Excellent investment opportunity near Oklahoma State University! 4-unit property with all units currently leased. Strong rental history with consistent occupancy. Each unit has 2 bedrooms and 1 bathroom. Recent capital improvements include new roof, parking lot resurfacing, and exterior paint. Gross annual rental income of $48,000.',
                'features' => ['Central AC', 'Central Heat', 'Garage', 'Laundry Room', 'On-Site Parking'],
                'photos' => [
                    'https://images.pexels.com/photos/1115804/pexels-photo-1115804.jpeg?auto=compress&cs=tinysrgb&w=800',
                    'https://images.pexels.com/photos/280222/pexels-photo-280222.jpeg?auto=compress&cs=tinysrgb&w=800',
                ],
                'contact_name' => 'M&T Realty Group',
                'contact_email' => 'admin@mandreality.com',
                'contact_phone' => '(405) 964-8485',
                'is_active' => true,
                'is_mls_listed' => true,
                'mls_number' => 'MLS-2026-0008',
                'listing_tier' => 'mls',
                'has_professional_photos' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
                'approved_by' => $admin->id,
                'latitude' => 36.1156,
                'longitude' => -97.0584,
            ],
            [
                'user_id' => $admin->id,
                'property_title' => 'Restored Craftsman in Midtown Tulsa',
                'developer' => 'McIntosh Construction',
                'property_type' => 'single-family-home',
                'status' => 'for-sale',
                'listing_status' => 'for_sale',
                'price' => 389000,
                'address' => '1821 S Boston Ave',
                'city' => 'Tulsa',
                'state' => 'Oklahoma',
                'zip_code' => '74119',
                'subdivision' => 'Midtown',
                'school_district' => 'Tulsa Public Schools',
                'grade_school' => 'Lee Elementary',
                'middle_school' => 'Edison Preparatory',
                'high_school' => 'Edison High School',
                'bedrooms' => 4,
                'bathrooms' => 2.5,
                'full_bathrooms' => 2,
                'half_bathrooms' => 1,
                'sqft' => 2800,
                'lot_size' => 8712,
                'acres' => 0.20,
                'year_built' => 1925,
                'description' => 'Beautifully restored 1920s craftsman home in historic Midtown Tulsa. Original hardwood floors, built-in cabinetry, and period details preserved throughout. Fully updated kitchen with custom cabinetry and marble countertops. Updated bathrooms with period-appropriate fixtures. New plumbing, electrical, and HVAC while maintaining historic charm. Walking distance to Cherry Street shops and restaurants.',
                'features' => ['Central AC', 'Central Heat', 'Hardwood Floors', 'Fireplace', 'Covered Patio', 'Mature Trees', 'Garage', 'Built-In Shelving', 'Original Woodwork'],
                'photos' => [
                    'https://images.pexels.com/photos/1029599/pexels-photo-1029599.jpeg?auto=compress&cs=tinysrgb&w=800',
                    'https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg?auto=compress&cs=tinysrgb&w=800',
                    'https://images.pexels.com/photos/2724749/pexels-photo-2724749.jpeg?auto=compress&cs=tinysrgb&w=800',
                    'https://images.pexels.com/photos/1571468/pexels-photo-1571468.jpeg?auto=compress&cs=tinysrgb&w=800',
                ],
                'contact_name' => 'M&T Realty Group',
                'contact_email' => 'admin@mandreality.com',
                'contact_phone' => '(405) 964-8485',
                'is_active' => true,
                'is_featured' => true,
                'is_mls_listed' => true,
                'mls_number' => 'MLS-2026-0009',
                'listing_tier' => 'mls',
                'has_professional_photos' => true,
                'has_virtual_tour' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
                'approved_by' => $admin->id,
                'latitude' => 36.1397,
                'longitude' => -95.9784,
            ],
            [
                'user_id' => $admin->id,
                'property_title' => 'New Construction in Deer Creek',
                'developer' => 'Homes by Taber',
                'property_type' => 'single-family-home',
                'status' => 'for-sale',
                'listing_status' => 'for_sale',
                'price' => 465000,
                'address' => '2200 W Memorial Rd',
                'city' => 'Edmond',
                'state' => 'Oklahoma',
                'zip_code' => '73013',
                'subdivision' => 'Deer Creek Estates',
                'school_district' => 'Deer Creek Public Schools',
                'grade_school' => 'Deer Creek Elementary',
                'middle_school' => 'Deer Creek Middle School',
                'high_school' => 'Deer Creek High School',
                'bedrooms' => 4,
                'bathrooms' => 3.5,
                'full_bathrooms' => 3,
                'half_bathrooms' => 1,
                'sqft' => 2850,
                'lot_size' => 10454,
                'acres' => 0.24,
                'year_built' => 2025,
                'description' => 'Brand new construction in the award-winning Deer Creek school district! Open-concept living with 10-foot ceilings, a gourmet kitchen with oversized island, and luxury vinyl plank flooring. Primary suite features a spa-like bathroom with free-standing tub and walk-in tile shower. Covered back patio with gas stub-out for outdoor kitchen. Full builder warranty included.',
                'features' => ['Central AC', 'Central Heat', 'Granite Countertops', 'Walk-In Closet', 'Garage', 'Sprinkler System', 'Energy Efficient', 'Covered Patio', 'Gas Fireplace'],
                'photos' => [
                    'https://images.pexels.com/photos/1438832/pexels-photo-1438832.jpeg?auto=compress&cs=tinysrgb&w=800',
                    'https://images.pexels.com/photos/2227832/pexels-photo-2227832.jpeg?auto=compress&cs=tinysrgb&w=800',
                    'https://images.pexels.com/photos/2062426/pexels-photo-2062426.jpeg?auto=compress&cs=tinysrgb&w=800',
                    'https://images.pexels.com/photos/3935350/pexels-photo-3935350.jpeg?auto=compress&cs=tinysrgb&w=800',
                ],
                'contact_name' => 'M&T Realty Group',
                'contact_email' => 'admin@mandreality.com',
                'contact_phone' => '(405) 964-8485',
                'is_active' => true,
                'is_featured' => true,
                'is_mls_listed' => true,
                'mls_number' => 'MLS-2026-0010',
                'listing_tier' => 'mls',
                'has_professional_photos' => true,
                'has_virtual_tour' => true,
                'has_video' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
                'approved_by' => $admin->id,
                'latitude' => 35.6650,
                'longitude' => -97.5600,
            ],
            [
                'user_id' => $admin->id,
                'property_title' => 'Lakefront Property on Grand Lake',
                'developer' => null,
                'property_type' => 'single-family-home',
                'status' => 'for-sale',
                'listing_status' => 'for_sale',
                'price' => 549000,
                'address' => '57120 E Hwy 28',
                'city' => 'Grove',
                'state' => 'Oklahoma',
                'zip_code' => '74344',
                'subdivision' => 'Grand Lake Shores',
                'school_district' => 'Grove Public Schools',
                'grade_school' => 'Grove Elementary',
                'middle_school' => 'Grove Middle School',
                'high_school' => 'Grove High School',
                'bedrooms' => 4,
                'bathrooms' => 3,
                'full_bathrooms' => 3,
                'half_bathrooms' => 0,
                'sqft' => 2600,
                'lot_size' => 15682,
                'acres' => 0.36,
                'year_built' => 2008,
                'description' => 'Stunning lakefront home with private dock on Grand Lake O\' the Cherokees. Wall-to-wall lake views from the open living area, primary suite, and expansive back deck. Two-story great room with stone fireplace. Walkout basement with kitchenette, bedroom, and direct lake access. Perfect as a primary residence or vacation home.',
                'features' => ['Central AC', 'Central Heat', 'Fireplace', 'Hardwood Floors', 'Granite Countertops', 'Covered Patio', 'Garage', 'Lake View', 'Private Dock', 'Walkout Basement'],
                'photos' => [
                    'https://images.pexels.com/photos/2287310/pexels-photo-2287310.jpeg?auto=compress&cs=tinysrgb&w=800',
                    'https://images.pexels.com/photos/2581922/pexels-photo-2581922.jpeg?auto=compress&cs=tinysrgb&w=800',
                    'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=800',
                ],
                'contact_name' => 'M&T Realty Group',
                'contact_email' => 'admin@mandreality.com',
                'contact_phone' => '(405) 964-8485',
                'is_active' => true,
                'is_showcase' => true,
                'is_mls_listed' => true,
                'mls_number' => 'MLS-2026-0011',
                'listing_tier' => 'mls',
                'has_professional_photos' => true,
                'has_virtual_tour' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
                'approved_by' => $admin->id,
                'latitude' => 36.5937,
                'longitude' => -94.7698,
            ],
            [
                'user_id' => $admin->id,
                'property_title' => 'Move-In Ready Townhome in Owasso',
                'developer' => 'Simmons Homes',
                'property_type' => 'condos-townhomes-co-ops',
                'status' => 'for-sale',
                'listing_status' => 'for_sale',
                'price' => 235000,
                'address' => '9300 N 129th E Ave',
                'city' => 'Owasso',
                'state' => 'Oklahoma',
                'zip_code' => '74055',
                'subdivision' => 'Bailey Ranch',
                'school_district' => 'Owasso Public Schools',
                'grade_school' => 'Bailey Elementary',
                'middle_school' => 'Owasso 7th Grade Center',
                'high_school' => 'Owasso High School',
                'bedrooms' => 3,
                'bathrooms' => 2.5,
                'full_bathrooms' => 2,
                'half_bathrooms' => 1,
                'sqft' => 1850,
                'lot_size' => null,
                'year_built' => 2021,
                'description' => 'Low-maintenance living in the sought-after Owasso school district! This nearly-new townhome features an open floor plan, quartz countertops, stainless steel appliances, and a private fenced patio. HOA covers lawn care, exterior maintenance, and community pool access. Minutes from shopping and dining on 96th St.',
                'features' => ['Central AC', 'Central Heat', 'Granite Countertops', 'Stainless Steel Appliances', 'Walk-In Closet', 'Garage', 'Community Pool', 'Fenced Yard'],
                'photos' => [
                    'https://images.pexels.com/photos/1643389/pexels-photo-1643389.jpeg?auto=compress&cs=tinysrgb&w=800',
                    'https://images.pexels.com/photos/1080721/pexels-photo-1080721.jpeg?auto=compress&cs=tinysrgb&w=800',
                    'https://images.pexels.com/photos/2030037/pexels-photo-2030037.jpeg?auto=compress&cs=tinysrgb&w=800',
                ],
                'contact_name' => 'M&T Realty Group',
                'contact_email' => 'admin@mandreality.com',
                'contact_phone' => '(405) 964-8485',
                'is_active' => true,
                'is_mls_listed' => true,
                'mls_number' => 'MLS-2026-0012',
                'listing_tier' => 'mls',
                'has_professional_photos' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
                'approved_by' => $admin->id,
                'latitude' => 36.2698,
                'longitude' => -95.8547,
            ],

            // ── PENDING (UNDER CONTRACT) ──────────────────────────
            [
                'user_id' => $admin->id,
                'property_title' => 'Under Contract — Bungalow in Brookside',
                'developer' => null,
                'property_type' => 'single-family-home',
                'status' => 'pending',
                'listing_status' => 'pending',
                'price' => 295000,
                'address' => '3521 S Peoria Ave',
                'city' => 'Tulsa',
                'state' => 'Oklahoma',
                'zip_code' => '74105',
                'subdivision' => 'Brookside',
                'school_district' => 'Tulsa Public Schools',
                'grade_school' => 'Lee Elementary',
                'middle_school' => 'Edison Preparatory',
                'high_school' => 'Edison High School',
                'bedrooms' => 3,
                'bathrooms' => 2,
                'full_bathrooms' => 2,
                'half_bathrooms' => 0,
                'sqft' => 1800,
                'lot_size' => 7405,
                'acres' => 0.17,
                'year_built' => 1940,
                'description' => 'Charming bungalow in the heart of Brookside with original character and modern updates. This home received multiple offers within the first weekend on the market.',
                'features' => ['Central AC', 'Central Heat', 'Hardwood Floors', 'Fireplace', 'Fenced Yard'],
                'photos' => [
                    'https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg?auto=compress&cs=tinysrgb&w=800',
                ],
                'contact_name' => 'M&T Realty Group',
                'contact_email' => 'admin@mandreality.com',
                'contact_phone' => '(405) 964-8485',
                'is_active' => true,
                'is_mls_listed' => true,
                'mls_number' => 'MLS-2026-0013',
                'listing_tier' => 'mls',
                'has_professional_photos' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
                'approved_by' => $admin->id,
                'latitude' => 36.1098,
                'longitude' => -95.9747,
            ],

            // ── SOLD ──────────────────────────────────────────────
            [
                'user_id' => $admin->id,
                'property_title' => 'SOLD — Modern Home in Jenks',
                'developer' => 'Taber Homes',
                'property_type' => 'single-family-home',
                'status' => 'sold',
                'listing_status' => 'sold',
                'price' => 340000,
                'address' => '525 W Main St',
                'city' => 'Jenks',
                'state' => 'Oklahoma',
                'zip_code' => '74037',
                'subdivision' => 'Riverwalk',
                'school_district' => 'Jenks Public Schools',
                'grade_school' => 'West Elementary',
                'middle_school' => 'Jenks Middle School',
                'high_school' => 'Jenks High School',
                'bedrooms' => 4,
                'bathrooms' => 3,
                'full_bathrooms' => 3,
                'half_bathrooms' => 0,
                'sqft' => 2400,
                'lot_size' => 7841,
                'acres' => 0.18,
                'year_built' => 2020,
                'description' => 'Beautiful modern home near the Arkansas River in the acclaimed Jenks school district. Sold with multiple offers within the first week on market — another successful M&T Realty Group sale!',
                'features' => ['Central AC', 'Central Heat', 'Granite Countertops', 'Stainless Steel Appliances', 'Garage', 'Sprinkler System'],
                'photos' => [
                    'https://images.pexels.com/photos/1438832/pexels-photo-1438832.jpeg?auto=compress&cs=tinysrgb&w=800',
                ],
                'contact_name' => 'M&T Realty Group',
                'contact_email' => 'admin@mandreality.com',
                'contact_phone' => '(405) 964-8485',
                'is_active' => true,
                'is_mls_listed' => true,
                'mls_number' => 'MLS-2026-0014',
                'listing_tier' => 'mls',
                'has_professional_photos' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
                'approved_by' => $admin->id,
                'sold_at' => now()->subDays(14),
                'testimonial' => 'M&T Realty Group sold our home in just 5 days with multiple offers above asking price. Their marketing was incredible and the process was completely stress-free.',
                'testimonial_name' => 'Sarah & Mike Thompson',
                'latitude' => 36.0228,
                'longitude' => -95.9683,
            ],
            [
                'user_id' => $admin->id,
                'property_title' => 'SOLD — Family Home in Mustang',
                'developer' => 'Ideal Homes',
                'property_type' => 'single-family-home',
                'status' => 'sold',
                'listing_status' => 'sold',
                'price' => 310000,
                'address' => '804 W Elm Crossing',
                'city' => 'Mustang',
                'state' => 'Oklahoma',
                'zip_code' => '73064',
                'subdivision' => 'Elm Creek',
                'school_district' => 'Mustang Public Schools',
                'grade_school' => 'Mustang Creek Elementary',
                'middle_school' => 'Mustang North Middle School',
                'high_school' => 'Mustang High School',
                'bedrooms' => 4,
                'bathrooms' => 2.5,
                'full_bathrooms' => 2,
                'half_bathrooms' => 1,
                'sqft' => 2200,
                'lot_size' => 8712,
                'acres' => 0.20,
                'year_built' => 2017,
                'description' => 'Spacious family home in the Mustang school district. Sold within 30 days at full asking price thanks to M&T Realty Group\'s strategic pricing and professional marketing.',
                'features' => ['Central AC', 'Central Heat', 'Granite Countertops', 'Fenced Yard', 'Garage', 'Covered Patio', 'Sprinkler System'],
                'photos' => [
                    'https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&w=800',
                ],
                'contact_name' => 'M&T Realty Group',
                'contact_email' => 'admin@mandreality.com',
                'contact_phone' => '(405) 964-8485',
                'is_active' => true,
                'is_mls_listed' => true,
                'mls_number' => 'MLS-2026-0015',
                'listing_tier' => 'mls',
                'has_professional_photos' => true,
                'approval_status' => 'approved',
                'approved_at' => now(),
                'approved_by' => $admin->id,
                'sold_at' => now()->subDays(30),
                'testimonial' => 'From our first meeting to closing day, M&T was professional, responsive, and genuinely cared about getting us the best outcome. We couldn\'t have asked for a better experience.',
                'testimonial_name' => 'The Rodriguez Family',
                'latitude' => 35.3844,
                'longitude' => -97.7245,
            ],
        ];

        foreach ($properties as $propertyData) {
            Property::create($propertyData);
        }

        $this->command->info('Created ' . count($properties) . ' M&T Realty Group listings!');
    }
}
